### ISSUE TITLE
Are vsco journals and vsco collections the same thing?

### ISSUE THREAD

**Issue by github-userx** [mvabdi/vsco-scraper#13]

**Comment by mvabdi** [comment]
They are not. Journals are like photo albums while collections are sort of like retweets of other photos.

**Comment by github-userx** [comment]
Interesting, thanks! Because github.com/mikf/gallery-dl <http://github.com/mikf/gallery-dl> apparently only can get regular posts and collections, so no journals.

And again many thanks for creating such an awesome tool with vsco-scraper! (It’s more powerful for vsco than gallery-dl but I also love that with gallery-dl we got a tool capable of scraping so many different sites).
