### ISSUE TITLE
Is it possible to save downloaded content to different specified directory ?

### ISSUE THREAD

**Issue by CaolyX9** [mvabdi/vsco-scraper#15]
I would like to download images to a different destination. Is it possible ?

**Comment by mvabdi** [comment]
I'll merge previous pull requests and then see if I can add it.

**Comment by mvabdi** [comment]
I'll leave this open to anyone who wants to do a PR. I'll merge it if so.

**Comment by mvabdi** [comment]
I'm pretty sure that just calling it in a different directory would work

`cd whateverdir`

then

`vsco-scraper whoever -i`

Above should work

I'll close this issue as you can just do above, no real need for a PR
