### ISSUE TITLE
Sometimes new image does not download immediately

### ISSUE THREAD

**Issue by martro2** [mvabdi/vsco-scraper#17]
I've seen images being downloaded a full hour after it was uploaded. Can you try to find out what causes this?

**Comment by mvabdi** [comment]
I leave this open to anyone willing to do a PR.

My guess for this would be rate limiting by VSCO, so it could be you're downloading too often.

**Comment by mvabdi** [comment]
Have you faced this since?

**Comment by mvabdi** [comment]
Closing this as no updates in nearly a year.
