### ISSUE TITLE
Problems with Linux filesystem

### ISSUE THREAD

**Issue by ghost** [mvabdi/vsco-scraper#2]
Thanks for the previous fix on #1, I managed to get it working on my Windows install though I would like to run this automatically on a Linux instance.

I get the following error on Debian
```bash
debian@debian:$ vsco-scraper USERNAME --getImages
Traceback (most recent call last):
  File "/usr/local/bin/vsco-scraper", line 11, in <module>
    load_entry_point('vsco-scraper==0.36', 'console_scripts', 'vsco-scraper')()
  File "/usr/local/lib/python3.5/dist-packages/vsco_scraper-0.36-py3.5.egg/vscoscrape/vscoscrape.py", line 181, in main
  File "/usr/local/lib/python3.5/dist-packages/vsco_scraper-0.36-py3.5.egg/vscoscrape/vscoscrape.py", line 20, in __init__
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/path/to/folder/\\USERNAME'
```

**Comment by mvabdi** [comment]
Does the make directory work? As in a folder named USERNAME is made?

**Comment by ghost** [comment]
No folders are created, and it seems to be an issue with being in that directory (it was `/mnt/shares/vsco/`).

I've returned to my home directory and tried again and it seems to download the images (gets the correct amount of images, shows the download loading bar progress) though no folders are shown in my home directory `~/`

**Comment by mvabdi** [comment]
I uploaded another version to pip, 0.37, let me know if it doesnt work

**Comment by ghost** [comment]
Thank you! It's working fine now (even in the directory).

**Comment by mvabdi** [comment]
@bamtan thank you for pointing out errors
