### ISSUE TITLE
KeyError: 'sites' 

### ISSUE THREAD

**Issue by christoarmani** [mvabdi/vsco-scraper#24]
Hello, first off I want to say this is an awesome tool with so few contributors. 

I ran into an issue on two profiles where this traceback error occurred. 

Traceback (most recent call last):
```
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\Scripts\vsco-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('vsco-scraper==0.60', 'console_scripts', 'vsco-scraper')())
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\vscoscrape\vscoscrape.py", line 656, in main
    scraper = Scraper(args.username)
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\vscoscrape\vscoscrape.py", line 31, in __init__
    self.newSiteId()
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\vscoscrape\vscoscrape.py", line 56, in newSiteId
    self.siteid = res.json()["sites"][0]["id"]
KeyError: 'sites'
```

I get this error when I call `$ vsco-scraper <username> -i` 

If I try to call <username> within a file I get
`<username> crashed`

**Comment by mvabdi** [comment]
Are you just putting the usernames into the files?

To run with the file, the command would be something like

`vsco-scraper usernames.txt -m`

The file should have the names in sequential order i.ie

`bob`
`jack`

Let me know if that doesn't change anything.

**Comment by christoarmani** [comment]
Yes, I put the usernames into a file when I try running the two affected profiles within a text file I get a return of `<username> crashed`. I get the KeyError: 'sites' when I run ` vsco-scraper <username> -i` command for the individual profile.

**Comment by mvabdi** [comment]
So it's only a subset of users not working? In that case, you should verify that they did not change their usernames on vsco.

The cachehit feature is meant to keep the script working when usernames change.

**Comment by christoarmani** [comment]
Thanks! I totally forgot to check that! It appeared that one of the profiles no longer exists and the other I missed a letter when I copied.

**Comment by mvabdi** [comment]
Glad it's working!

**Comment by christoarmani** [comment]
May I suggest tweaking the error statement? To say, `Error. No profile found. Please verify that the profile exists.`
