### ISSUE TITLE
ModuleNotFoundError: No module named 'constants'

### ISSUE THREAD

**Issue by yoohooie** [mvabdi/vsco-scraper#3]
Followed the ReadMe but when I run it on my profile I get the above error.

I can see the constants.py file in the package directory, so I don't know why I'm getting this error, Using the latest python 3 package on a Windows 10 machine. 

Any insights as to why this would happen? 

Thanks

**Comment by mvabdi** [comment]
It now works in a similar test environment, marking as closed.


Update using the latest pypi package, 0.48
