### ISSUE TITLE
Is there a way to specify a folder/directory to save downloaded content?

### ISSUE THREAD

**Issue by swaggyP36000** [mvabdi/vsco-scraper#30]
It's slightly outside my scope of knowledge, and since the path is not globally defined in the script and there are multiple functions, it seems very tedious to change all the variables. Is there an easier way that I'm missing?

**Comment by parkerr82** [comment]
Go check for the site ID first, and if it fails then skip everything else
and move to the next one.

**Comment by swaggyP36000** [comment]
I am not sure what this means... I just meant is there an option I'm missing? Or what is the full process to manually change where the users' folders are created? By default, since I'm on Linux, it just creates the folders in my Home directory, but that just pollutes the Home directory, so if there is a way to direct the script to make the folders somewhere else, that's what I need.

**Comment by bialyrycerz** [comment]
From the readme:
_Images are downloaded into the <current directory/<username> folder_
So, you can cd to the directory where you want the photos, then run the script, and the photos will be saved there.
I don't see any way to use a config file or option to specify the location.

**Comment by mvabdi** [comment]
Exactly as @bialyrycerz has said. How I conceived the script is that you just cd into the directory you want.
