### ISSUE TITLE
What happened to vsco.co/ajxp?

### ISSUE THREAD

**Issue by ccrenfroe** [mvabdi/vsco-scraper#31]
Code seems to be broken now because this API route no longer exists?

if you try going to `https://vsco.co/ajxp`

```
{"status":0,"errorType":"This API does not even exist 1"}
```

**Comment by mvabdi** [comment]
I'll be doing the rest of the discussion on #32, this is related.

**Comment by mvabdi** [comment]
The mystery is solved, the api is now on: http://vsco.co/api/2.0/ and requires a bearer token
