### ISSUE TITLE
Thumbnails request

### ISSUE THREAD

**Issue by petertriell** [mvabdi/vsco-scraper#4]
Hi - is it possible to as a feature so that thumbnails are downloaded for all images, rather than full size?

Or is it easy for me to modify that myself?

Apologies if this is a dumb question. This is a great script, thank you!

**Comment by mvabdi** [comment]
By thumbnails do you mean the images you see on the vsco grid or pictures
that size of the profile picture.

**Comment by petertriell** [comment]
I'll be honest I'm not sure, just the smallest possible image - I'm looking to be able to download a gallery, look at it in low red, then selectively track down shots I like in full res.

**Comment by petertriell** [comment]
To help explain, I have a bad internet connection with a data cap, so I'm looking to minimize my downloads.

**Comment by mvabdi** [comment]
After looking through a test VSCO json for a thumbnail version of an image, I couldn't find any. What I could do is use a different Python library to get a thumbnail version of said picture downloaded, though I am not sure if that is going to help with the data cap very much.

**Comment by petertriell** [comment]
Ah that's no good. I'll just have to cope.

Appreciate your great script and your help.
