### ISSUE TITLE
Videos no longer downloading

### ISSUE THREAD

**Issue by Tyen3** [mvabdi/vsco-scraper#51]
It seems that VSCO has been migrating their site to sit behind Cloudflare, as I've encountered various issues these past few weeks where Cloudflare was blocking content. Starting this past Friday, I noticed that the content of .mp4 files that vsco-scraper downloaded were actually Cloudflare 404 Object Not Found HTML files. Investigating further, it appears that the VSCO API returns video links that point to objects that are no longer accessible. This can be observed visiting VSCO with a web browser and viewing network traffic with browser tools; the site attempts to retrieve these objects, but fails due to the 404s.

It appears that VSCO may have recently turned video uploading/hosting into a "premium" feature, resulting in existing videos to turn into still frame previews for non-premium accounts. 

With video objects now being inaccessible, the only "fix" to this might be to modify the scraper to download the still frame preview of the video as a .jpg instead of an .mp4. I may attempt to write a patch for this if I have time.

**Comment by timbo0o1** [comment]
Hey could you show me an example where you experience this issue?

**Comment by Tyen3** [comment]
> Hey could you show me an example where you experience this issue?

Account "leahfactor" is a decent example. There are four .mp4 files downloaded: 

`1553396042.mp4  1554592255.mp4  1555422046.mp4  1576460004.mp4
`

All of which are actually Cloudflare 404 HTML.

**Comment by Tyen3** [comment]
While the above example is still valid, I did come across an account that I am able to pull mp4's from: aleeman53. So perhaps VSCO is in the process of moving stuff around, and this will eventually work again. I guess time will tell.

**Comment by timbo0o1** [comment]
> While the above example is still valid, I did come across an account that I am able to pull mp4's from: aleeman53. So perhaps VSCO is in the process of moving stuff around, and this will eventually work again. I guess time will tell.

Was about to say that it works on other profiles.
We will see where this goes or if it's a rare occurrence.

**Comment by Tyen3** [comment]
It appears VSCO has completed whatever backend work they were doing, and I am now able to download mp4s again. Closing this ticket out.
