### ISSUE TITLE
Problems with Linux filesystem on v0.47

### ISSUE THREAD

**Issue by bamtan** [mvabdi/vsco-scraper#6]
Hi, when issuing the following command: `vsco-scraper vsco_user -i` 

It creates a new folder called `my_username\vsco_user` inside my /home/ directory (`/home/my_username\vsco_user`). This makes the program require elevation to run, and outputs permission errors.

```bash
Traceback (most recent call last):
  File "/usr/local/bin/vsco-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/vscoscrape/vscoscrape.py", line 211, in main
    scraper = Scraper(args.username)
  File "/usr/local/lib/python3.5/dist-packages/vscoscrape/vscoscrape.py", line 24, in __init__
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/my_user\\vsco_user'
```

**Comment by mvabdi** [comment]
Was it working previously?

**Comment by bamtan** [comment]
I haven't used any other version aside from the fix made in #2, v0.37

**Comment by harangutang** [comment]
I forked it and changed a few lines and on my debian machine it solved the issue. You should be able to see it on my page.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bamtan** [comment]
Can confirm that harangutang's fix from his fork is working on my Linux machine.

**Comment by mvabdi** [comment]
If it works on Windows as well, make a pull request. Thanks for the fix!

**Comment by bamtan** [comment]
Tested on Windows 10 1803, working correctly. @harangutang are you able to make a pull request?
