### ISSUE TITLE
ImportError: No module named vscoscrape

### ISSUE THREAD

**Issue by hasangokdag** [mvabdi/vsco-scraper#7]
Hello,
When i run:
`vsco-scraper username -i`
I get:
```
File "/home/user/.local/bin/vsco-scraper", line 7, in <module>
    from vscoscrape import main
  File "/home/user/.local/lib/python2.7/site-packages/vscoscrape/__init__.py", line 1, in <module>
    from vscoscrape.vscoscrape import *
ImportError: No module named vscoscrape
```
I think I followed the README well but I m probably doing something wrong with Python versions(I have 2.7-3.5.2 and 3.7 somehow). I am geting this error on Linux by the way.

**Comment by mvabdi** [comment]
Use python 3, not python 2.7.

The version you installed this on is python 2.7

**Comment by mvabdi** [comment]
Is this now fixed?

**Comment by hasangokdag** [comment]
I couldn't find how to run it with 2.7 so i switched to macos and runned it with 3.6.5. If i could have found a way to run it with python3 it would probably have worked so we may close this issue.
