### ISSUE TITLE
No such file or directory: "<the username>"

### ISSUE THREAD

**Issue by zerowidthzen** [mvabdi/vsco-scraper#8]
It seems to think that the username argument is referring to a file or directory.

```
bash-3.2$ vsco-scraper <username> --all
Traceback (most recent call last):
  File "/usr/local/bin/vsco-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vscoscrape/vscoscrape.py", line 251, in main
    with open(args.username,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '<the username>'
```

**Comment by mvabdi** [comment]
I'll look into this this weekend, currently busy.

**Comment by mvabdi** [comment]
I was looking through the code trying to figure out why it wasn't making a folder until I remembered this one uses a filename, since it's meant for multiple users

For example:
`vsco-scraper <filename-of-text-file> --all`

Perhaps I should be more explicit in the README
